services:
  mongo-secondary:
    image: mongo:5
    container_name: mongo-secondary
    restart: unless-stopped
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongo-secondary:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-cluster
networks:
  mongo-cluster:
    driver: bridge
