services:
  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
    networks:
      - memcached-network
networks:
  memcached-network:
    name: "memcached-network"
    driver: bridge
