services:
  ipfs:
    image: ipfs/kubo:v0.36.0
    ports:
      - '4001:4001'
      - '5001:5001'
      - '8080:8080'
    volumes:
      - ./data:/data/ipfs
      - ./scripts:/scripts
    environment:
      - IPFS_PATH=/data/ipfs
      - IPFS_PROFILE=server
    entrypoint: /scripts/start-ipfs.sh
    networks:
      - ipfs-network
networks:
  ipfs-network:
    name: "ipfs-network"
    driver: bridge
