services:
  weaviate:
    image: semitechnologies/weaviate:1.32.5
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: '20'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
