services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql/
      - ./init.db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - mysql-network
networks:
  mysql-network:
    name: "mysql-network"
    driver: bridge
