services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    env_file:
      - .env  # 加载 .env 文件中的环境变量
    volumes:
      - ./data:/var/lib/mysql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    command:
      --default-authentication-plugin=mysql_native_password
      --lower_case_table_names=1
