services:
  mysql:
    restart: always
    image: mysql:latest
    container_name: mysql
    volumes:
      - ~/dockercompose/mysql/data/db:/var/lib/mysql/
      - ~/dockercompose/mysql/mysql-3346.sock:/var/run/mysql.sock
      - ~/dockercompose/mysql/data/conf:/etc/mysql/conf.d
      - ~/dockercompose/mysql/data/sql:/opt/sql
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    command:
      --default-authentication-plugin=mysql_native_password
      --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: zhf123..
      MYSQL_DATABASE: brinjal_ai
      TZ: Asia/Shanghai
