services:  
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9011"
    ports:
      - "9000:9000"
      - "9011:9011"
    volumes:
      - ./data:/data

