services:  
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    env_file:
      - .env
    command: server /data --console-address ":9011"
    ports:
      - "9000:9000"
      - "9011:9011"
    volumes:
      - ./data:/data
    networks:
      - minio-network
networks:
  minio-network:
    name: "minio-network"
    driver: bridge


